# Gateway — pipeline
GW_UPSTREAM_BEFORE_ACK = "CRASH_GATEWAY_UPSTREAM_BEFORE_ACK"
GW_DOWNSTREAM_BEFORE_SEND = "CRASH_GATEWAY_DOWNSTREAM_BEFORE_SEND"
GW_DOWNSTREAM_BEFORE_ACK = "CRASH_GATEWAY_DOWNSTREAM_BEFORE_ACK"
GW_BEFORE_FINALIZE = "CRASH_GATEWAY_BEFORE_FINALIZE"

# Gateway — estado
GW_BEFORE_PERSIST_CONNECTED = "CRASH_GATEWAY_BEFORE_PERSIST_CONNECTED"
GW_AFTER_PERSIST_CONNECTED = "CRASH_GATEWAY_AFTER_PERSIST_CONNECTED"
GW_BEFORE_PERSIST_DATOS_ENVIADOS = "CRASH_GATEWAY_BEFORE_PERSIST_DATOS_ENVIADOS"
GW_AFTER_PERSIST_DATOS_ENVIADOS = "CRASH_GATEWAY_AFTER_PERSIST_DATOS_ENVIADOS"
GW_BEFORE_PERSIST_QUERY = "CRASH_GATEWAY_BEFORE_PERSIST_QUERY"
GW_AFTER_PERSIST_QUERY = "CRASH_GATEWAY_AFTER_PERSIST_QUERY"

# Workers
BEFORE_FINISHED_CONFIRMATION = "CRASH_BEFORE_FINISHED_CONFIRMATION"
PRE_BARRERA = "CRASH_PRE_BARRERA"
AFTER_FLUSH = "CRASH_AFTER_FLUSH"
AFTER_PERSIST = "CRASH_AFTER_PERSIST"

# Watchdog
LEADER_MID_ELECTION = "CRASH_LEADER_MID_ELECTION"
WD_POST_TOPOLOGY_SAVE = "CRASH_WD_POST_TOPOLOGY_SAVE"
WD_POST_TOPOLOGY_LOAD = "CRASH_WD_POST_TOPOLOGY_LOAD"
WD_PRE_PUBLISH_CAIDA = "CRASH_WD_PRE_PUBLISH_CAIDA"
WD_POST_LEADER_DECLARE = "CRASH_WD_POST_LEADER_DECLARE"
